/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package epi

import spock.lang.Specification
import java.nio.file.Path
import java.nio.file.Paths

class AppTest extends Specification {
    def "application has a greeting"() {
        setup:
        def app = new App()

        when:
        def result = app.greeting

        then:
        result != null
    }
}
