/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package epi;
import java.nio.file.Path;
import java.nio.file.Paths;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
	Path path = Paths.get(".").toAbsolutePath();
    	System.out.println(path);
        System.out.println(new App().getGreeting());
    }
}
